name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test Parse
        run: go test -v ./parse

      - name: Test Evaluate
        run: go test -v ./evaluate

      - name: Test Complex
        run go test -v ./types/mathgroups/complex
